# Fetching the minified node image on apline linux
FROM node:slim

# Declaring env
ENV NODE_ENV development

# Install Python
RUN apt-get update && apt-get install -y python3 build-essential

# Install git
RUN apt-get install -y git
RUN apt-get install -y yarn

# Setting up the work directory
WORKDIR /express-docker

# Copying all the files in our project
COPY server .

# Installing dependencies
RUN npm install

# RUN mkdir -p /home/user

# Starting our application
CMD [ "npm", "run", "dev" ]

# Exposing server port
# EXPOSE 9000
